name: GPG Validity Check

on:
  workflow_call:
    secrets:
      commit-user-name:
        required: true
        default: Joshua Sinyor
      commit-user-email:
        required: true
        default: 74914999+JoshSinyor@users.noreply.github.com
      gpg-private-key-block:
        required: true
        default: ${{ secrets.GPG_PRIVATE_KEY_BLOCK }}
      gpg-passphrase:
        required: true
        default: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  gpg-validity-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Register Successful Request
      run: echo "Successfully requested."

#     - name: Import GPG Key
#       run: echo "$BASE64_ENCRYPTED_GPG_KEY_BLOCK" | base64 -d | gpg -q --batch --yes --passphrase "$GPG_PASSPHRASE" --import
#
#     - name: Extract keyid and Set GPG_KEYID
#       run: echo "GPG_KEYID=$(gpg -k | awk '/^ / {print $1}')" >> $GITHUB_ENV
#
# # Update GPG key
#
#     - name: Update GPG Key and Warn if Failure
#       run: |
#         if [ `gpg --refresh-keys $GPG_KEYID &> >(grep -c 'failed')` -ne 0 ] ; then
#           echo "::warning title="Failed to Update GPG Key"::Keyserver refresh failed."
#         fi
#
# # Check if GPG key has expired
#
#     - name: Check if GPG Key Expired
#       run: |
#         if [ `gpg -k $GPG_KEYID &> >(grep -c 'expired')` -ne 0 ] ; then
#           echo "::warning title=GPG Certificate Expired::This repository's GPG certificate has expired."
#           exit 1
#         fi
#
# # Extract key expiry and today dates, and set GPG_EXPIRY
#
#     - name: Extract key expiry and Set GPG_EXPIRY
#       run:
#         exp_date=$(gpg -k $GPG_KEYID | awk '/expire/ {print substr($6,1,10); exit}' | { read exp ; date -d "$exp" +"%s" ; })
#         now_date=$(date +"%Y-%m-%d" | { read now ; date -d "$now" +"%s" ; })
#
#         echo "GPG_EXPIRY=$(( ($exp_date - $now_date) / 86400 ))" >> $GITHUB_ENV
#
# # Notify of days before GPG key expires
#
#     - name: Warn of GPG Key Expiry in Advance
#       if: ${{ (env.GPG_EXPIRY == 0) || (env.GPG_EXPIRY <= 7) && (env.GPG_EXPIRY >= 0) }}
#       run: |
#         echo "::warning title=GPG Certificate Expiring Soon::This repository's GPG certificate will expire in ${{ env.GPG_EXPIRY}} days."
#
#     - name: Notify of GPG Expiry Date
#       run: echo "::notice title=GPG Certificate Expiration::This repository's GPG certificate will expire in ${{ env.GPG_EXPIRY }} days."
