name: Retrieve GPG Credentials

on: workflow_call

jobs:
  retrieve-gpg-credentials:
    runs-on: ubuntu-latest

    env:
      GPG_PRIVATE_KEY_BLOCK: null
      GPG_PASSPHRASE: null

    steps:
    - name: Checkout
      uses: actions/checkout@v2

# Retrieve credentials

# Set output values
